/*==========================================================
            SQL EDA PROJECT - SALES ANALYSIS
==========================================================*/

USE DataWarehouseAnalytics



--- 1. DATABASE EXPLORATION


-- Q1. View all tables in the database
SELECT *
FROM INFORMATION_SCHEMA.TABLES;

-- Q2. View all columns of the Customers table
SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers';



--- 2. DIMENSION EXPLORATION


-- Q3. List all unique countries
SELECT DISTINCT country
FROM gold.dim_customers;

-- Q4. List all product categories
SELECT DISTINCT category
FROM gold.dim_products;

-- Q5. List all product subcategories
SELECT DISTINCT subcategory
FROM gold.dim_products;

-- Q6. List all product names
SELECT DISTINCT product_name
FROM gold.dim_products;



--- 3. DATE EXPLORATION


-- Q7. Find the first and last order date
SELECT MIN(order_date) AS first_order_date, MAX(order_date) AS last_order_date
FROM gold.fact_sales;

-- Q8. Calculate the order history in years
SELECT DATEDIFF(YEAR, MIN(order_date), MAX(order_date)) AS order_history_years
FROM gold.fact_sales;



--- 4. MEASURE EXPLORATION


-- Q9. Calculate the total sales
SELECT SUM(sales_amount) AS total_sales
FROM gold.fact_sales;

-- Q10. Calculate the total quantity sold
SELECT SUM(quantity) AS total_quantity
FROM gold.fact_sales;

-- Q11. Calculate the average selling price
SELECT AVG(price) AS average_price
FROM gold.fact_sales;

-- Q12. Calculate the total number of orders
SELECT COUNT(DISTINCT order_number) AS total_orders
FROM gold.fact_sales;

-- Q13. Calculate the total number of products
SELECT COUNT(product_key) AS total_products
FROM gold.dim_products;

-- Q14. Calculate the total number of customers
SELECT COUNT(customer_key) AS total_customers
FROM gold.dim_customers;

-- Q15. Calculate the total number of customers who placed an order
SELECT COUNT(DISTINCT customer_key) AS customers_with_orders
FROM gold.fact_sales;

--- ALL KEY BUSINESS METRICS (Single Query)

SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales

UNION ALL SELECT 'Total Quantity', SUM(quantity) FROM gold.fact_sales

UNION ALL SELECT 'Average Price', AVG(price) FROM gold.fact_sales

UNION ALL SELECT 'Total Orders', COUNT(DISTINCT order_number) FROM gold.fact_sales

UNION ALL SELECT 'Total Products', COUNT(product_key) FROM gold.dim_products

UNION ALL SELECT 'Total Customers', COUNT(customer_key) FROM gold.dim_customers

UNION ALL SELECT 'Customers With Orders', COUNT(DISTINCT customer_key) FROM gold.fact_sales;



--- 5. MAGNITUDE ANALYSIS


-- Q16. Calculate total customers by country
SELECT country, COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;


-- Q17. Calculate total customers by gender
SELECT gender, COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;


-- Q18. Calculate total products by category
SELECT category, COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;


-- Q19. Calculate the average product cost by category
SELECT category, AVG(cost) AS average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC;


-- Q20. Calculate total revenue generated by each category
SELECT p.category, SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;


-- Q21. Calculate total revenue generated by each customer
SELECT c.customer_key, c.first_name, c.last_name, SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c ON f.customer_key = c.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_revenue DESC;


-- Q22. Calculate total quantity sold by country
SELECT c.country, SUM(f.quantity) AS total_quantity
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_quantity DESC;



--- 6. RANKING ANALYSIS


-- Q23. Find the Top 5 Products that generated the highest revenue
SELECT TOP 5
    p.product_name, SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p ON f.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC;


-- Q24. Find the Bottom 5 Products that generated the lowest revenue
SELECT TOP 5
    p.product_name, SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p ON f.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue ASC;


-- Q25. Rank all products based on total revenue using ROW_NUMBER()
SELECT p.product_name, SUM(f.sales_amount) AS total_revenue,
ROW_NUMBER() OVER (ORDER BY SUM(f.sales_amount) DESC) AS product_rank
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p ON f.product_key = p.product_key
GROUP BY p.product_name;


-- Q26. Display the Top 5 Products using ROW_NUMBER()
SELECT *
    FROM (SELECT p.product_name, SUM(f.sales_amount) AS total_revenue,
    ROW_NUMBER() OVER (ORDER BY SUM(f.sales_amount) DESC) AS product_rank
    FROM gold.fact_sales AS f
    LEFT JOIN gold.dim_products AS p ON f.product_key = p.product_key
    GROUP BY p.product_name) AS ranked_products
WHERE product_rank <= 5;


-- Q27. Find the Top 10 Customers who generated the highest revenue
SELECT TOP 10
    c.customer_key, c.first_name, c.last_name, SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c ON f.customer_key = c.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_revenue DESC;


-- Q28. Find the Bottom 3 Customers based on total orders placed
SELECT TOP 3
    c.customer_key, c.first_name, c.last_name, COUNT(DISTINCT f.order_number) AS total_orders
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c ON f.customer_key = c.customer_key
GROUP BY c.customer_key, c.first_name,c.last_name
ORDER BY total_orders ASC;
